services:
  server:
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npx ng serve --configuration=development --port 80 --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 80:80
