services:
  server:
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 80:80
