version: '3.8'

services:
  nginx:
    image: ${REGISTRY}/eemployee-management-system-nginx:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: nginx/Dockerfile.prod
    ports:
      - 443:443
      - 80:80
    depends_on:
      - server
  server:
    image: ${REGISTRY}/employee-management-system-server:${IMAGE_TAG}
