version: '3.8'

services:
  nginx:
    image: huzaifaqayyum/employee-management-nginx:latest
    build:
      context: ./
      dockerfile: nginx/Dockerfile.prod
    ports:
      - 443:443
      - 80:80
    depends_on:
      - server
  server:
    image: huzaifaqayyum/employee-management-server:latest
