FROM node:16.19.0-alpine3.16 AS build-stage

WORKDIR /app

COPY frontend/package*.json .
RUN npm ci && npm cache clean --force

COPY frontend .
RUN [ "npm", "run", "build" ]


FROM nginx:stable-alpine AS PROD

WORKDIR /app

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf